### ISSUE TITLE
Clean Architecture

### ISSUE THREAD

**Issue by LucasBlackP** [LucasBlackP/iOSfromScratch#10]
https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html
https://clean-swift.com
https://hackernoon.com/introducing-clean-swift-architecture-vip-770a639ad7bf

**Comment by PhatDoThanh** [comment]
https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html
